version: "3.9"

services:
  app:
    build: .
    environment:
      - DEBUG=app:*
    tty: true
    ports:
      - '53005:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'npm run dev'
#    command: tail -f /dev/null
    restart: always
