version: "3.9"

services:
  app:
    build: .
    environment:
      - DEBUG=app:*
#      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    ports:
      - '53005:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'yarn && yarn dev'
#    command: sh -c 'npm run dev'
#    command: sh -c 'npm i && npm run dev'
#    command: sh -c 'npm start'
#    command: tail -f /dev/null
    restart: always
