version: "3.9"

services:
  app:
    image: mcr.microsoft.com/playwright:v1.34.0-jammy
    environment:
      - DEBUG=app:*
    stdin_open: true
    tty: true
    ports:
      - '53005:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'npm i && npm run dev'
#    command: tail -f /dev/null
    restart: always
